### PR TITLE
Add (Vi)ZDoom environments

### PR DESCRIPTION
**Pull request by Miffyli**
Adds few basic ViZDoom environments by not using image pixels (so it is now just "ZDoom" :D) but instead passes the list of (all) objects in the level, plus game variables / location of the player etc.

TODO: 
* [ ] Figure out the poetry lock stuff (atm it is a mess). Comments/help welcomed. Ideally it should be optional like the griddly thing.
* [ ] Add few other basic scenarios and debug performance (should be able to learn in all of them). Agent is learning in HealthGathering task as expected \o/

### CODE REVIEW

**Comment by vwxyzjn** [comment]
Hey, @Miffyli would you mind elaborating on the poetry issues?

**Comment by Miffyli** [comment]
@vwxyzjn If you try `poetry add vizdoom` the building will fail on something about distutils (or setuptools). You can bypass this by opening poetry shell and using pip there to install vizdoom.

**Comment by vwxyzjn** [comment]
Related to #96. Probably the easiest way for the users is to do `poetry install` first then do `pip install` for packages that don't play nicely with poetry.

**Comment by cswinter** [comment]
@Miffyli Rotating positions of all entities to align with the direction the actor is facing is quite helpful in CodeCraft and I imagine it could be useful for Doom as well. I've implemented it as a generic transform that can be enabled with the `--translate` flag as part of https://github.com/entity-neural-network/incubator/pull/157

**Comment by Miffyli** [comment]
Hey! Sorry for the long quietness :)

If we only want some basic scenarios (i.e. the ones listed), then the main work relies on double-checking that the scenarios are running correctly. The agent should be able to improve over time, too (works with visual-based RL).

One thing I will probably need help with is correct way of updating the poetry stuff ˆˆ'. What files should be updated (e.g. do locks need to be updated, too?), and need to try Costa's trick for vizdoom.

**Comment by cswinter** [comment]
Not an expert on this poetry stuff yet, what we can always do is just bypass poetry with `poetry run pip install ...` which should work just when using only pip. Maybe we don't need to make the `vizdoom` dependency optional, in that case this recipe has worked for me to update the relevant pyproject and lock files:

```
cd enn_zoo
poetry update vizdoom
# or: `poetry add vizdoom` if not added yet
cd ..
poetry update vizdoom
poetry install
```

**Pull request closed without merging**
