### PR TITLE
Fix #32

### LINKED ISSUE #32: InputNorm the running sum of square computation is incorrect
Merged with #30 in `ppo/train.py` the following code to update the sum of squares for a batch
```python
            # This is probably not quite right because it applies multiple updates simultaneously.
            self.squares_sum = self.squares_sum + (
                (input - self.mean) * (input - new_mean)
            ).sum(dim=0)
``` 
does not compute the correct sum of squares based on the formulas of [Welford's method](https://www.johndcook.com/blog/standard_deviation/)

### PR DESCRIPTION
**Pull request by Theomat**
Fix #32 based on the parallel algorithm see [wikipedia](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) section "Parallel algorithm" and *Chan, Tony F.; Golub, Gene H.; LeVeque, Randall J. (1979), "Updating Formulae and a Pairwise Algorithm for Computing Sample Variances.", Technical Report STAN-CS-79-773, Department of Computer Science, Stanford University.*

### CODE REVIEW

**Comment by cswinter** [comment]
Nice! Could you add a test as well?

**Comment by Theomat** [comment]
Done!

**Comment by cswinter** [comment]
Excellent! I've fixed up the CI config to run tests on PRs as well: https://github.com/entity-neural-network/incubator/pull/35
Could you rebase onto latest `main` and push the branch again to see if it worked and tests get triggered?

**Comment by cswinter** [comment]
Looks like code formatter is failing, you can fix with `pip install black==19.10b0` and running `black .`. In VSCode, you can also set up format on save to make it automatic.

**Comment by Theomat** [comment]
Perhaps you can add a `CONTRIBUTING.md` with all the requirement that need to be fulfilled, so there's no need to say "format with black, we use pytest and so on" in each PR?

**Comment by cswinter** [comment]
🎉🎉🎉

**Pull request merged**
