### PR TITLE
Bam4d/generic entity ids

### LINKED ISSUE #14: Add entity-gym bindings for Griddly.
There are single-agent, multi-agent and RTS games in Griddly, so maybe its best to focus on one type at first. RTS is probably the most fitting as it has many different types of entities and attributes, but also might be harder to get a good baseline/benchmark. There are some other super simple MA environments we can make/use also for testing.

* Use `get_state()` method to grab the state dict, 
* Transform it into the right format 
* Produce embeddings

### PR DESCRIPTION
**Pull request by Bam4d**
More information on this in here -> #74 

I've also modified the "cherry-pick" env and the "count" env to use strings as entityIDs as tests for guaranteeing #74.

Also Griddly now partially trains using EntityIDs that are hashes of underlying pointers in c++. HOWEVER.... it still cannot solve the environment. At the moment, the agent learns to avoid the spikes (which kill it) but does not learn to actually create any "clusters".

I'm not sure whether this is a tuning issue, or an underlying bug or limitation of the pooling layers. I could do with some more perspective from @cswinter or anyone who knows more about the pooling implementation.

image

Closes #14

### CODE REVIEW

**Comment by Bam4d** [comment]
With some hyperparameter search the environment starts to learn!
image

`./train.py --gym-id=GDY-Clusters-0 --exp-name=griddly-clusters-test --track --total-timesteps=4000000 --num-envs=64 --learning-rate=0.0005 --ent-coef=0.1 --d-model=128 --d-qk=128 --n-layer=3`

**Comment by cswinter** [comment]
Very cool!
Our architecture does quite poorly if you just feed it raw x/y positions. I would expect much faster training with https://github.com/entity-neural-network/incubator/issues/104 (maybe with rotation as well?). I've not tried this yet, but I think some kind of better positional encoding would also solve the issue, especially once we have an actual transformer backbone.

**Review by cswinter — APPROVED** [review]

**Comment by Bam4d** [comment]
> Very cool! Our architecture does quite poorly if you just feed it raw x/y positions. I would expect much faster training with #104 (maybe with rotation as well?). I've not tried this yet, but I think some kind of better positional encoding would also solve the issue, especially once we have an actual transformer backbone.

Actually in this case because its a single level with full observability, the x,y positions probably dont even matter because the network would probably just remeber a sequence of moves. In the case where the env is procedurally generated I agree the positional encodings/rotation normalization would be a useful normalizing feature for sure. You can configure griddly to give you these positional encoding/invariances automatically.

**Comment by cswinter** [comment]
I see, makes sense. Though even if it just learns a specific sequence of moves, it still needs to figure out what state in the sequence it is in, which could be easier with better positional encodings. Less clear though.

**Pull request merged**
