### PR TITLE
Adapt poetry as package manager

### PR DESCRIPTION
**Pull request by vwxyzjn**
This PR adapts the entire project to use poetry as the package manager. See the following demo.

[asciicast](https://asciinema.org/a/452597)

One issue is when doing `poetry install` `torch-scatter` throws an error. I think this is because `torch-scatter` never explicitly says it depends on `torch` so when doing parallelized installation it throws the error. To fix it, simply run `poetry install` again.

### CODE REVIEW

**Comment by vwxyzjn** [comment]
installation issue will likely be fixed after #68 #69

**Comment by cswinter** [comment]
Beautiful 🤩

The GitHub action and `CONTRIBUTING.md` will need to be updated.
Also, do we still need the `setup.py` files? They seem redundant with the `pyproject.toml`s

**Comment by vwxyzjn** [comment]
> Also, do we still need the setup.py files?

Nope :) I will delete them and update the CI and `CONTRIBUTING.md`

**Comment by vwxyzjn** [comment]
Updating black to fix a python 3.9 issue: https://stackoverflow.com/questions/69912264/python-3-9-8-fails-using-black-and-importing-typed-ast-ast3

**Comment by vwxyzjn** [comment]
@cswinter how would you feel upgrading black to the latest version? 

otherwise it seems updating typed-ast would also work.

**Comment by cswinter** [comment]
> @cswinter how would you feel upgrading black to the latest version?

SGTM

**Comment by vwxyzjn** [comment]
The CI passed but note the newer version of black does incur slightly different formatting behaviors.

**Comment by vwxyzjn** [comment]
Merging now.

**Pull request merged**
